### ISSUE TITLE
wrong spelling in contributor list

### ISSUE THREAD

**Issue by anselm-baur** [nils-braun/b2luigi#103]
thank you for adding me to the contributor list, buuuuut Baur is written without an 'e' :)

**Comment by nils-braun** [comment]
How about a PR @anselm-baur :-D

**Comment by meliache** [comment]
Thanks for reporting. I've been doing more typos recently, when it comes to PR's I've become a bit more hurried or maybe just tired :sweat_smile:. I think Anselm knows how to do a PR so I just quickly fixed this.

**Comment by anselm-baur** [comment]
> How about a PR @anselm-baur :-D

I was in issue mode :see_no_evil:, thanks @meliache
