### ISSUE TITLE
Rename `MasterTask`'s in examples to something less culturally sensitive

### ISSUE THREAD

**Issue by meliache** [nils-braun/b2luigi#117]
We have already made our main branch `main` and we could follow through by replacing all examples in the documentation where the implementation of `luigi.WrapperTask`  is named `MasterTask` by something else. Suggestions:

- `MainTask`
- `WrapperTask` -- In this case the base name would be the same as the class it inherits from, just in a different namespace. Maybe it would be better a meaningful prefix to convey what it does, e.g. `ReconstructionWrapperTask` or `AnalysisWrapperTask`

**Comment by philiptgrace** [comment]
The systematic corrections framework uses `AggregatorTask`, which I quite like.

**Comment by nils-braun** [comment]
Both are fine with me - thanks for this reasonable change @meliache
