### ISSUE TITLE
Deprecated `message` property for exceptions is used

### ISSUE THREAD

**Issue by meliache** [nils-braun/b2luigi#119]
In [b2luigi.core.utils.map_folder](https://github.com/nils-braun/b2luigi/blob/main/b2luigi/core/utils.py#L272-L288) an exception is re-raised with a modified exception message, where the original message is appended via`ex.message`. 
``` python
    except AttributeError as ex:
        raise type(ex)(
            "Could not determine the current script location. "
            "If you are running in an interactive shell (such as jupyter notebook) "
            "make sure to only provide absolute paths in your settings.\nMore Info:\n" +
            ex.message
        ).with_traceback(sys.exc_info()[2])
```
I get an error in python 3.9 that the exception has no `message` property, but this seems to be already deprecated since python 2.6 (see [PEP-352](https://www.python.org/dev/peps/pep-0352/#retracted-ideas)).

The obvious solution would be to just use the `str(ex)` or a format string like `f"More info: {ex}"`. But before fixing this in a PR, my questions is what's the "best" way to re-raise an exception with a modified message in python 3. The `raise type(ex)(...).with_traceback(...)` construct seems a bit cumbersome to me, is it really necessary? I admit I don't fully understand it, maybe @FelixMetzner who introduced this code in #34 (thanks for that) can help.

**Comment by nils-braun** [comment]
If you raise an exception within handling another exception, both stack traces and exception messages will be shown (... while handling ...).
You can also choose what is shown with something like `raise Ex1 from Ex2`, but that should not be necessary here (as the outer exception is the default)

**Comment by meliache** [comment]
> If you raise an exception within handling another exception, both stack traces and exception messages will be shown (... while handling ...).
I saw this when the bug occured, then I got another exception that `ex.message` doesn't exist :wink: 

I'll then go forward with the suggested fix.
