### ISSUE TITLE
Issue with large projects separated into subfolders

### ISSUE THREAD

**Issue by Bilokin** [nils-braun/b2luigi#147]
Hello,

thanks for adding the support for multiple sub-directories in the grid projects, i.e. that have multiple `sub*` folders in their output, but unfortunately, I think there is a bug linked to it:
When `b2luigi` moves the downloaded output from temporary folders of `sub00`, `sub01`, `subXX`,  to the output folder, let's call it `result/`, the contents of `sub00` folder is not in the `result/`, but I suspect that it is in the `result/sub00` folder.
I tried to run the  [this code](https://github.com/nils-braun/b2luigi/blob/a81a814821b3380c5504ccd95fb613f3ad5a34c3/b2luigi/batch/processes/gbasf2.py#L711) in the python interpreter using `sub00` and `sub01` input folders and not existing output folder `./result` and I get the following tree:
```
./result
    sub01_content.root
    sub00/
         sub00_content.root
```
This is not expected by the tasks downstream and I would prefer that the output folder would contain all files from all `sub*` folders directly. There shouldn't be any conflicts in the file names, but one has to check for that anyway.

**Comment by meliache** [comment]
Tasks copied over from the duplicate issue #148:
- [ ] fix moving so that all root files are flat in the output dir
- [ ] encapsulate moving code into its own function (for easier testing)
- [ ] write test with dummy `.root` files

**Comment by meliache** [comment]
I now created a draft PR #150  where I changed the moving function to move ROOT files individually into the final output directory, with some more checks in place so it _should_ work, but I still haven't tested it yet, which I will do now.
