### ISSUE TITLE
b2luigi file paths depend on order in which parameters are declared

### ISSUE THREAD

**Issue by elimik31** [nils-braun/b2luigi#16]
It's nice that the directory structure contains the metadata on the used luigi parameters. It might be intended behavior, that the order of the parameters in the path is the order in which they are declared. However, this means that you might get very different behavior of your task depending on the order you declare the parameters. It's best explained with this example:

```python
import b2luigi

class TaskXY(b2luigi.Task):
    "Some task requiring some luigi parameters"
    x = b2luigi.Parameter()
    y = b2luigi.Parameter()

    def output(self):
        yield self.add_to_output("output.txt")

    def run(self):
        with open(self.get_output_file_name("output.txt"), "w") as file:
            file.write(f"{self.x}{self.y}")

class TaskYX(b2luigi.Task):
    "Same as task YX, but declaring parameters in a different order"
    y = b2luigi.Parameter()
    x = b2luigi.Parameter()

    def output(self):
        yield self.add_to_output("output.txt")

    def run(self):
        with open(self.get_output_file_name("output.txt"), "w") as file:
            file.write(f"{self.x}{self.y}")

class MasterTask(b2luigi.WrapperTask):
    def requires(self):
        yield TaskYX(x=1, y=2)
        yield TaskXY(x=1, y=2)

if __name__ == "__main__":
    b2luigi.process(MasterTask(), workers=1)

```
This task results in the following directory structure:
```
├── x=1
│   └── y=2
│       └── output.txt
└── y=1
    └── x=2
        └── output.txt
```
The output `output.txt` is thus duplicated, even though it is created both times with the same parameter set (it thus can't be thought of as a set) and contains both times the same string "12". However, when you change `TaskYX` that it defines first x, then y, then you get the expected output
```
└── x=1
    └── y=2
        └── output.txt
```
You can't change the fact the the signatures of a task/class depends on the order of its static members. But maybe, when creating the output paths, it is possible to sort them somehow (e.g. alphabetically).  I imagine this might be problematic when incrementally adding new tasks in subsequent runs, resulting in a need to re-shuffle the directory structure to make place for new parameters. Maybe this is a fundamental limitation of the simple directory tree approach and changing it might make things worse? At least it does not result in wrong results, only duplication which does not do too much harm.

**Comment by nils-braun** [comment]
The idea I had with this is exactly as you described and also a different feature: if you have subtasks (aka derived tasks) you will get a nice hierarchical structure (for example one task generating the input for another task, whereas the second task has probably exactly the same variables as the input task plus some additional ones).

It also gives the user the possibility to actually choose the order - e.g. you may want to have the experiment number before the event number (although alphabetically it would be the other way round).

I actually started the development with alphabetically sorted parameters, but have switched to this behaviour because I was annoyed during by PhD thesis :-)

**Comment by nils-braun** [comment]
Sorry it took to long to answer the issue...

**Comment by elimik31** [comment]
No problem, it's minor. In practice I didn't have any cases as the example described above, I just sometimes got annoyed that I had some outputfiles in a directory `A/B` and outputfiles of other tasks with same parameters, but defined in different order, in `B/A`. But it's not something that cause major problems.

**Comment by nils-braun** [comment]
If you want it in your specific use case, what you can always do is overwrite the function `get_serialized_parameters` (or even `get_params`) of the tasks. In principle something like
```python
def get_params(self):
    params = super8).get_params()
    return sorted(params)
```
should work (I did not test it, just written spontaneously). You can either do this by "patching" the `b2luigi.Task` class or by providing your own base class.
