### ISSUE TITLE
Bug with htcondor job status property

### ISSUE THREAD

**Issue by eckerpatrick** [nils-braun/b2luigi#164]
In #158 the `get_job_status()` function in the subclass `HTCondorProcess` was changed to a property and is therefore no longer callable.
Nevertheless it gets called in https://github.com/nils-braun/b2luigi/blob/main/b2luigi/batch/processes/__init__.py line 135.
I think this is a bug.

**Comment by meliache** [comment]
Thanks to both of for finding the source of the error and for fixing it so fast :+1:
