### ISSUE TITLE
fei_merge_files command is about to have its name changed

### ISSUE THREAD

**Issue by meliache** [nils-braun/b2luigi#33]
https://github.com/nils-braun/b2luigi/blob/b1e3b2c2005ea8847e65a9f5abf900e989e91cf4/b2luigi/basf2_helper/tasks.py#L113

The `fei_merge_files` command that is used in the ntuple merger task might have its name changed soon, because there's an open [issue](https://agira.desy.de/browse/BII-3905) that analysistools should follow the `b2...` convention (maybe `b2fei-merge-fei-output`). I just made a small not really related [PR](https://stash.desy.de/projects/B2/repos/software/pull-requests/6174/overview) to the `fei_merge_files` and as a result the analysis librarian asked me if I could work on the issue.

Secondly, there's also a separate already existing `b2file-merge` command. If possible I would suggest to use that, since we aren't doing anything FEI-related, but I assume there's a reason I don't know why we can't use it, maybe because of the restrictions that it has, that are described in its help string:

> This program is intended to merge files created by separate basf2 jobs. It's
> similar to hadd but does correctly update the metadata in the file and merges
> the objects in the persistent tree correctly.
> 
> The following restrictions apply:
>
>   - The files have to be created with the same release and steering file
>   - The persistent tree is only allowed to contain FileMetaData and objects
>     inheriting from Mergeable and the same list of objects needs to be present
>     in all files.
>   - The event tree needs to contain the same DataStore entries in all files.

**Comment by meliache** [comment]
So I the PR for renaming the tools received some comments by Martin Ritter.

> `b2file-merge` is to merge RootOutput files. This `fei_merge_files` is a bit of a hybrid as it merges ntuples by just calling `hadd` but if the file is a RootOutput file it will only merge the ProcessStatistics, not the actual events in the file. So this is a specialized tool.

Good to know. Maybe we could just use `hadd`? Also he was against using a `b2...` name, as that only should be used for tools for normal users and tools for expert users should be not as easy to discover. I now renamed it under his suggestion to `analysis-fei-mergefile` and created a redirection bash script for the old `fei_merge_files`, so that it will still work, but print a deprecation warning first. So this issue is not urgent in any way.

**Comment by FelixMetzner** [comment]
Using `hadd` directly also has it's flaws, as this will cause problems if too many files are provided to be merged, if I remember correctly. So, there is a reason for doing it this way in some cases.

The original commit message was:
> like 'hadd', but avoids fiery memory death when merging moduleStatistics files for FEI. Can be generalized for other use cases.

**Comment by meliache** [comment]
Okay I see. By the way, my PR is merged and script has been renamed to `analysis-fei-mergefiles`, but the old command still works, just gives a deprecation warning (it is a bash script that runs the new command). So I think we could use a try..except to try both names.

**Comment by FelixMetzner** [comment]
Yeah, it would be nice if you take care of the backward compatibility for older basf2 versions :)
Try except with the new version first is the obvious solution, I guess. Thanks for taking care of this!

**Comment by meliache** [comment]
Now addressed this in https://github.com/nils-braun/b2luigi/pull/36, should have done this immediately after the basf2 PR was merged instead of talking so much.
