### ISSUE TITLE
Improve dirac proxy validity time handling

### ISSUE THREAD

**Issue by meliache** [nils-braun/b2luigi#48]
When working with gbasf2 subprocesses in the gbasf2 BatchProcess, in addition to a gbasf2 environment most commands also need an alive dirac proxy. On the command line, users initialize it with `gb2_proxy_init -g belle`, then they get asked for their certificate pasdsword and then it stays alive for 24 hours. So in my wrapper, I check if there is still an alive/valid dirac proxy on the system and run the initalize command only if there is not. The main reason I did that was to ensure the proxy is valid but also I did 
want to reduce superfluous password prompts.

@philiptgrace made me aware [here](https://github.com/nils-braun/b2luigi/pull/46#issuecomment-705289731) that users can set the proxy validity time explicitly via `-v HH:MM` and this can surprisingly be much more than 24 hours. He also suggested [here](https://github.com/nils-braun/b2luigi/pull/46#issuecomment-705915640) that we could consider renewing the proxy not when the remaining validity time reaches 0, but before that for increased stability.

> In addition to having a user option called something like gb2_proxy_time (to be passed to the -v flag), it may be useful to have an option gb2_proxy_minimum_time (defaulting to 0), to re-initialise the proxy if the time left is less than the given number of hours. The usecase I am imagining is a long submission/monitoring/downloading time where the user doesn't want their proxy to timeout part way through.

Though I currently have a branch in progress where I want to implement that this check is done for every `run_with_gbasf` call, so I'm not sure whether this is important, but still I don't see why not. 

- [ ] add setting for proxy validity time
- [ ] maybe increase default time
- [ ] re-initialize dirac proxy before remaining validity time reaches 0 and add setting for that minimum time

**Comment by philiptgrace** [comment]
I cherry-picked your commits and implemented the default & minimum proxy lifetimes on my branch [feature/use-gbasf2-subprocess-to-check-if-dirac-proxy-is-alive](https://github.com/philiptgrace/b2luigi/tree/feature/use-gbasf2-subprocess-to-check-if-dirac-proxy-is-alive).
