### ISSUE TITLE
Future proof gbasf2 batch by downloading all sub<xy>  directories

### ISSUE THREAD

**Issue by meliache** [nils-braun/b2luigi#80]
At the moment, the gbasf2 batch process expects that all output files of a job are in a `sub00` subdirectory. However, it is planned that for gbasf2 projects with more than 1000 outputs, new `sub<xy>` directories will be created, so it would be good to look for such directories as well in the gbasf2 output download. At the moment it would be just for future-proofing, so I don't plan working on this immediately, but created this issue as a reminder for myself and for b2luigi gbasf2 users. 

I found that out in an email to comp-users-forum

> Subject: Re: [comp-users-forum:1701] [dc_operations] new gbasf2 folder structure issue
> Date: Wed, 10 Mar 2021 23:44:23 CET

> If your jobs produce single-output, then you will have 1K files per datablock
> (subXX). Of course for now we are still limiting the jobs per project to 1K
> while we validate we can proceed with massive submission, then for now the
> output is expected to be only inside sub00.
> 
> Nothing prevents that jobs have multiple output, but in that case, in the current implementation you will see more > 1K files per datablock. 
> We are working to fix this, by design only 1K files are expected inside the datablock and some of our tools may not work properly. 

Implementing support for other subxy-directories will be easier once gbasf2 allows downloading files without explicitly providing the sub-directory. Also this might be achieved with wildcard-downloads, which hopefully will get more stable in the future.

**Comment by philiptgrace** [comment]
According to [BIIDCD-1390](https://agira.desy.de/browse/BIIDCD-1390), the automatic usage of the `sub<xy>` directories for projects with more than 1000 jobs will be enabled in the next release of BelleDIRAC (v5r1p3).

In [BIIDCD-1020](https://agira.desy.de/browse/BIIDCD-1020), `gb2_ds_get` was modified so all subdirectories of the given LPN are downloaded (unless `--noSubDir` is passed).

**Comment by meliache** [comment]
Thanks for the info and for looking into the old issues instead of creating a new one. Getting this information in advance makes the transition much less stressful than being surprised by a new release.

At the moment we have hardcoded the `/sub00` part of the LPN, because in a previous release there was a bug that resulted in a dataset not being downloaded if the sub00 part was not added. Am I right to assume that in the current release `v5r1p2` the download now even works when omiting the `sub00` from the LPN? I think I heard it somewhere, but currently can't find that in the [release notes](https://confluence.desy.de/display/BI/GBasf2+Releases). Probably just should test it.

I'm think, upon a successful download, should we copy the output ROOT files from all `sub<xy>` directories into a common directory? Or might that lead to file name crashes? Though I guess the job ID's in the file names should still be unique. Also, we might need to change how we check that the download was successful. b2luigi has a cross-check which compares the output of `gb2_ds_list` with the list of downloaded files, which back in the days I introduced since I didn't trust the gbasf2 download and further as a check of my own code. However, maybe we should start trusting gbasf2 and just assume that the download was complete if it says that no files failed and finishes with no error message. This would simplify a lot. Otherwise, we probably have to call `gb2_ds_list` for each of the `sub<xy>` directories.

**Comment by philiptgrace** [comment]
> Am I right to assume that in the current release v5r1p2 the download now even works when omiting the `sub00` from the LPN?

That's correct, `sub00` can be omitted in the current release.

> Otherwise, we probably have to call `gb2_ds_list` for each of the `sub<xy>` directories.

Calls to `gb2_ds_list` are already quite slow, so this would be quite time-consuming. For my own peace of mind, I really like the download cross-check you implemented; but if this is difficult to when there are `sub<xy>` directories, maybe we do need to just trust gbasf2.
