### ISSUE TITLE
Add static linter to workflows

### ISSUE THREAD

**Issue by meliache** [nils-braun/b2luigi#85]
At least for error-detection.

In #78 @nils-braun added github workflows and mentioned

> This can be expanded to also include things like stylechecks (pycodestyle, autopep8, black), isort, flake8 etc - but so far let's start with the basics.

I think what can't hurt in any way is to at least add static syntax checking for errors with `pyflakes` (the error-part of `flake8`) or the error-detection of `pylint`. I'm not against going the extra step to do style checks, but that is a bit more work since it involves discussing which style we actually want (e.g. line length), defining it in a config file and also mentioning it in the documentation, so imo this could be split into a separate PR. 

I have little experience with github workflows, but personally I have used [pre-commit](https://pre-commit.com) to do pre-commit checks locally. There's also a [pre-commit action](https://github.com/marketplace/actions/pre-commit) in the github marketplace and that would be my first idea how to implement style checks, since I find that extendible and straightforward and would feel confident of adding that myself. I just saw that there are also existing actions for e.g. flake8 that annotate the code, but I don't think we really need that. Or we could write our own actions. Don't know what's the most common approach.

**Comment by nils-braun** [comment]
I would also go with pre-commit. I share your good experiences.
